[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
yieldterminal = "313NKsMsgiA8uLp6y2dnfP1QzCQmZu9xkaaHSkMW6VL5"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "cargo test"

[hooks]
